In [1]:
import numpy as np
import matplotlib.pylab as plot
from astropy.io import ascii,fits
from scipy import interpolate
import grb_catalogs_copy
from BurstCube.LocSim.Detector import *
from BurstCube.LocSim.Spacecraft import *
from astropy.coordinates import SkyCoord
from astropy import units as u
from scipy.optimize import curve_fit

In [23]:
randgbm = np.random.rand(6,4)
#randgbm = randgbmexposures[:6,:4]
#numcols = len(randex[0]) 
#print(numcols)
#print(randgbmexposures)
#Order randgbmexposures into descending order
shape = np.shape(randgbm)
print(shape)
print(randgbm)

for column in randgbm.T:
    newrandgbm = -np.sort(-randgbm.T) 
fin = np.transpose(newrandgbm)
print(fin)

a = fin[1,:]
b = a.copy()
print(a)
print(b)

(6, 4)
[[0.01882939 0.24855068 0.74011366 0.65624892]
 [0.90825861 0.98958865 0.54399412 0.2095527 ]
 [0.84990504 0.57903835 0.05346336 0.74741246]
 [0.81332761 0.75673206 0.87235319 0.66250094]
 [0.21359755 0.84725625 0.25504342 0.78616853]
 [0.30940307 0.4386085  0.58876232 0.06512472]]
[[0.90825861 0.98958865 0.87235319 0.78616853]
 [0.84990504 0.84725625 0.74011366 0.74741246]
 [0.81332761 0.75673206 0.58876232 0.66250094]
 [0.30940307 0.57903835 0.54399412 0.65624892]
 [0.21359755 0.4386085  0.25504342 0.2095527 ]
 [0.01882939 0.24855068 0.05346336 0.06512472]]
[0.84990504 0.84725625 0.74011366 0.74741246]
[0.84990504 0.84725625 0.74011366 0.74741246]
